### ISSUE TITLE
Server is crashing on client disconnect after the heartbeat packet

### ISSUE THREAD

**Issue by belochub** [metarhia/jstp#217]
This bug occurred with JSTP version 0.5.2.
It is also highly possible that this issue isn't still fixed on master, it needs investigation.
The error log:
```js
TypeError: "listener" argument must be a function;
Connection.once (events.js:307:11);
Connection.setTimeout (/metarhia-jstp/lib/connection.js:258:8);
Connection._heartbeatCallback (/metarhia-jstp/lib/connection.js:208:8);
Connection.startHeartbeat (/metarhia-jstp/lib/connection.js:201:8);
Connection.<anonymous> (/metarhia-jstp/lib/server.js:110:18);
Object.onceWrapper (events.js:293:19); emitNone (events.js:86:13);
Connection.emit (events.js:188:7);
Connection._onTimeout (/metarhia-jstp/lib/connection.js:272:8);
ontimeout (timers.js:386:14);
tryOnTimeout (timers.js:250:5);
Timer.listOnTimeout (timers.js:214:5)
```
@aqrln, may you check this out please?

**Comment by belochub** [comment]
@aqrln, ping.
I believe, that it happens due to the `enroll`/`unenroll` usage for heartbeat timer creation.
Can you investigate this, please?

**Comment by nechaido** [comment]
@aqrln this error resurfaced again on node 8.4.0 on branch `add-distributed-benchmark` while running benchmark.
Steps to reproduce:
1. `node benchmark/distributed/master.js`
2. `node benchmark/distributed/server.js`
3. `node benchmark/distributed/workers -c 1000 -i 50 -w 3`
```

events.js:341
    throw new TypeError('"listener" argument must be a function');
    ^

TypeError: "listener" argument must be a function
    at Connection.once (events.js:341:11)
    at Connection.setTimeout (/home/nechaido/Projects/metarhia/jstp/lib/connection.js:308:10)
    at callback (/home/nechaido/Projects/metarhia/jstp/lib/connection.js:228:12)
    at Connection.startHeartbeat (/home/nechaido/Projects/metarhia/jstp/lib/connection.js:236:5)
    at Connection.connection.on (/home/nechaido/Projects/metarhia/jstp/lib/server.js:105:20)
    at emitTwo (events.js:125:13)
    at Connection.emit (events.js:213:7)
    at Connection._onSessionCreated (/home/nechaido/Projects/metarhia/jstp/lib/connection.js:489:10)
    at SimpleAuthPolicy.startSession (/home/nechaido/Projects/metarhia/jstp/lib/simple-auth-policy.js:33:5)
    at Connection._processHandshakeRequest (/home/nechaido/Projects/metarhia/jstp/lib/connection.js:466:17)
```
